spring.datasource.url=jdbc:mysql://127.0.0.1:3306/student_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dava@#1979
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ddl auto (create, create-drop, update, validate, none)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
